---
- name: Install Python
  hosts: pis
  gather_facts: no
  remote_user: pirate
  become: true
  become_method: sudo
  tasks:
    - name: Install Python
      raw: apt-get -y install python

- name: Setup Raspberry Pi Base system
  hosts: pis
  gather_facts: yes
  remote_user: pirate
  become: true
  become_method: sudo
  roles:
    - base

- name: Kubernetes Master
  hosts: master
  remote_user: pi
  become: true
  roles:
  - role: kubernetes
    mode: master

- name: Kubernetes Nodes
  hosts: nodes
  remote_user: pi
  become: true
  roles:
  - role: kubernetes
    mode: node

