- name: Create GlusterFS volumes directories 
  file: path=/var/gluster-fs/{{item}} state=directory mode=0775
  with_items:
    - "{{ groups['volumes'] }}"

- name: Configure GlusterFS peers
  shell: gluster peer probe {{item}}
  with_items:
    - "{{ groups['nodes'] }}"
  when: (inventory_hostname == groups['nodes'][0]) and (item != groups['nodes'][0])

- name: Build GlusterFS bricks list
  shell: echo {{groups['nodes'] | join(',')}} | sed "s%,%:/var/gluster-fs/{{item}} %g; s%$%:/var/gluster-fs/{{item}}%"
  register: gluster_bricks
  with_items:
    - "{{ groups['volumes'] }}"
  when: inventory_hostname == groups['nodes'][0]

- name: Create GlusterFS volumes
  shell: gluster volume info {{item.1}} || 
         gluster volume create {{item.1}} replica 2 transport tcp {{gluster_bricks.results[item.0].stdout}} force
  with_indexed_items:
    - "{{ groups['volumes'] }}"
  when: inventory_hostname == groups['nodes'][0]

- name: Start GlusterFS volumes
  shell: 'gluster volume info {{item}} | grep "Status: Started" || 
          gluster volume start {{item}}'
  with_items:
    - "{{ groups['volumes'] }}"
  when: inventory_hostname == groups['nodes'][0]