---
- name: Add and update packages
  include: apt.yml

- name: Setup GlusterFS
  include: glusterfs.yml

- name: Add Swapfile
  include: swap.yml
  vars:
    swap_file_path: "/swapfile"
    swap_file_size: "1G"

- name: Setup system parameters (boot, hosts, timzone)
  include: system.yml

- name: Configure Wifi
  include: wifi.yml
  when: wifi is defined

- name: Setup user
  include: user.yml

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for servers
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 5
    timeout: 600
  delegate_to: localhost
  become: no
