---
- name: Add and update packages
  include: apt.yml

- name: Add Swapfile
  include: swap.yml
  vars:
    swap_file_path: "/swapfile"
    swap_file_size: "1G"

- name: Setup system parameters (boot, hosts, timzone)
  include: system.yml

- name: Configure Wifi
  include: wifi.yml
  when: wifi is defined

- name: Setup user
  include: user.yml

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for servers
  become: no
  delegate_to: localhost
  wait_for: host={{ inventory_hostname }} state=started delay=10 timeout=300
