- name: Pin Docker to version {{ docker.version }} (the latest supported by Kubernetes)
  template: src=docker-apt-pin.txt dest=/etc/apt/preferences.d/docker

- name: Downgrade docker
  apt:
    state: present
    name: docker-ce={{ docker.version }}
    autoremove: yes
    force: yes

- name: Prepare docker expose args for service
  set_fact:
    dockerd_extra_args: "{{ '-H tcp://' + inventory_hostname + ':2375' if docker.expose_tcp else '' }}"

- name: Update docker service startup
  template: src=docker.service dest=/etc/systemd/system/docker.service
  register: result
  notify:
    - restart docker

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed

- name: Notify Docker service right now to restart
  meta: flush_handlers

- name: Set the iptables to FORWARD ACCEPT
  command: iptables -P FORWARD ACCEPT

- name: Save the iptables
  command: iptables-save
