- name: Reset if requested
  command: kubeadm reset
  when: reset
  tags:
    - reset

- name: Check for a running cluster
  command: kubectl get nodes
  become_user: pi
  register: kubectl_result
  failed_when: kubectl_result.rc == 2
  changed_when: kubectl_result.rc == 1

- block:

  - name: Setup master
    include: master.yml
    when: mode == "master"

  - name: Setup node
    include: node.yml
    when: mode == "node"

  when: kubectl_result.rc == 1 or reset
