apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
- addresses:
{% for item in groups['nodes'] %}
  - ip: {{item}}
{% endfor %}
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster-system
  namespace: kube-system
subsets:
- addresses:
{% for item in groups['nodes'] %}
  - ip: {{item}}
{% endfor %}
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: default
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
{% for item in groups['volumes'] %}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{item}}
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: {{item}}
    readOnly: false
{% endfor %}
