reset: false
overlay_network: flannel
network:
  service_subnet: 10.200.100.0/24
  pod_subnet: 10.1.0.0/16
images:
  flannel: quay.io/coreos/flannel:v0.7.1-arm
  weave: weaveworks/weave-kube:1.9.4
  weave_npc: weaveworks/weave-npc:1.9.4
k8s:
  pod_eviction_timeout: 20s
  node_monitor_grace_period: 40s
docker:
  storage_driver: overlay
  expose_tcp: true
debug_level: 2
