apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: whoami
        visualize: "true"
    spec:
      containers:
      - name: whoami
        image: 127.0.0.1:32500/hypriot/rpi-whoami
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          httpGet:
            path: /
            port: 8000
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
    visualize: "true"
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: whoami
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /whoami/
        backend:
          serviceName: whoami
          servicePort: 8000